### ISSUE TITLE
Has anyone done a security audit?

### ISSUE THREAD

**Issue by jakubLangr** [olegcherr/Reedy-for-Chrome#30]
I was surprised to have this extension removed from Chrome/Chrome Store, because I used it a while ago. But now with the whole TabSuspender debacle I worry about the privacy of this app. Has anyone done a security audit?

**Comment by amal** [comment]
Nope. But you can do the audit yourself. Code is rather simple and open.

Chrome Store removed extension because of policy compliance issue, not a security one.
Chrome Store now has more restrictions for extensions and requires a super very good reason for each permission.

Reedy extension uses 'tabs' permission for user convenience, but it's not considered as a valid reason by Google any more.

While true (almost all functions can work without this permission) such change requires additional time for development.
Extension will be returned to store after this change. But it will happen when developer will have free time for it..

BTW, any PR for this change can monstrously speed up this process!

**Comment by amal** [comment]
Aaand, Reedy is back in the store! :)

https://chromewebstore.google.com/detail/speed-reading/ihbdojmggkmjbhfflnchljfkgdhokffj/reviews?hl=en
